export const LOADING='LOADING'

export const C_WEATHERSUCCESS='C_WEATHERSUCCESS'
export const C_WEATHERFAILED='C_WEATHERFAILED'

export const FORECASTSUCCESS='FORECASTSUCCESS'
export const FORECASTFAILED='FORECASTFAILED'